[package]
name = "qbar-web"
version = "0.0.0"
edition = "2018"
readme = "README.md"
license-file = "../LICENSE"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
qbar = { path = "../qbar", features = ["shell", "web"] }
wasm-bindgen = "0.2"
wee_alloc = "0.4.5"
